spring:
  profiles:
    active: local
    group:
      local: local, common
      blue: blue, common
      green: green, common

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: blue

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080
  serverAddress: 54.180.238.186

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8081
  serverAddress: 54.180.238.186

serverName: green_server

---

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
  serverAddress: localhost

serverName: local_server

---

server:
  config:
    activate:
      on-profile: common

spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/exam?serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      encoding: UTF-8
      data-locations: classpath:/data.sql
#      mode: always

  jpa:
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        connection:
          CharSet: utf-8
          characterEncoding: utf-8
          useUnicode: true
#        dialect: org.hibernate.dialect.MySQLDialect
#    defer-datasource-initialization: true

logging.level:
  root: info
#  org.hibernate.SQL: debug
#  org.springframework.security: debug
#  org.springframework.web: debug


JWT_SECRET_KEY: ${JWT_SECRET_KEY}